apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kube-system
  name: kube-service-exporter
  labels:
    k8s-app: kube-service-exporter
  annotations:
    heaven.githubapp.com/inject-kube-metadata-env-vars-into-containers: "kube-service-exporter"
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: "50%"
  template:
    metadata:
      labels:
        k8s-app: kube-service-exporter
      annotations:
        service-discovery.datadoghq.com/kube-service-exporter.check_names: '["go_expvar"]'
        service-discovery.datadoghq.com/kube-service-exporter.init_configs: '[{}]'
        service-discovery.datadoghq.com/kube-service-exporter.instances: |
          [{ "expvar_url": "http://%%host%%:8080/debug/vars",
             "namespace": "kube_service_exporter.go_expvar",
             "tags": ["%%tags%%"] }]
    spec:
      serviceAccountName: kube-service-exporter
      containers:
      - name: kube-service-exporter
        image: kube-service-exporter
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          timeoutSeconds: 5
          httpGet:
            path: /healthz
            port: http
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]
        env:
        - name: KSE_CONSUL_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KSE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KSE_NODE_SELECTOR
          value: kubernetes.github.com/role=node
        - name: KSE_DOGSTATSD_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KSE_DOGSTATSD_PORT
          value: "28125"
        - name: KSE_SERVICES_ENABLED
          value: "false"
        - name: KSE_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: kubernetes_cluster_name
              name: kube-cluster-metadata
